export const visionStatementGPT = `
    Our Vision For MusicMe \n
    is to revolutionize the way people discover and enjoy music. 
    Our software application is designed to use cutting-edge technology to make music discovery effortless and personalized. 
    We believe that music has the power to bring people together and that everyone deserves to have access to their favorite tunes.
    
    Our mission is to leverage the power of the Spotify API and artificial intelligence models to build a platform that helps users find the music that they love. 
    We do this by using an innovative decision tree artificial intelligence model that takes into account a user's listening history and preferences to generate custom playlists.
    We believe that this approach offers a superior music discovery experience compared to traditional playlists generated by algorithms that don't take into account the unique tastes and preferences of each user.
    
    MusicMe also allows users to view and explore their own Spotify data, including their personal playlists, favorite songs, and top artists. 
    With MusicMe, users can dive deep into their own music preferences and explore new artists and genres that they may not have discovered otherwise.
    Our software application is built using React JavaScript and Node JS, two of the most popular technologies for developing modern web applications. 
    By leveraging these powerful tools, we have created a platform that is both user-friendly and scalable, ensuring that our users have the best possible experience.
    
    At MusicMe, we are passionate about music and technology, and we are committed to using our skills to make the world a better place. 
    Our vision is to create a platform that helps people discover new music, connect with others who share their passion for music, 
    and ultimately, enrich their lives through the power of music.
`